import java.awt.*;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.*;

public class SortingVisualizer extends JPanel {
    private int[] nums = new int[30];
    private String currentSortName = "None";
    private Thread sortingThread; // To manage the background execution

    public SortingVisualizer() {
        fillList(nums);
    }

    // --- BUTTON ACTIONS ---

    public void startAlgorithm(String name) {
        // 1. Stop any current sort immediately
        if (sortingThread != null && sortingThread.isAlive()) {
            sortingThread.interrupt();
            try {
                // Give the old thread a tiny moment to actually die
                sortingThread.join(50); 
            } catch (InterruptedException e) { }
        }

        // 2. HARD RESET: Generate a brand new array of exactly 30 elements
        this.nums = new int[30]; 
        fillList(this.nums);
        this.currentSortName = name;
        repaint(); // Show the new random bars immediately

        // 3. Start the chosen algorithm
        sortingThread = new Thread(() -> {
            try {
                // Pass the FRESHly generated this.nums to the methods
                switch (name) {
                    case "Sisyphus" -> sisyphusSort(this.nums);
                    case "Capitalism" -> capitalismSort(this.nums);
                    case "Communism" -> communismSort(this.nums);
                    case "Assassin" -> assasinSort(this.nums);
                    case "Phil Collins" -> philCollinsSort(this.nums);
                    case "Introvert" -> introvertSort(this.nums);
                    case "Midlife Crisis" -> midlifeCrisisSort(this.nums);
                    case "Bureaucracy" -> bureaucracySort(this.nums);
                }
                currentSortName += " (Finished)";
                repaint();
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            }
        });
        sortingThread.start();
    }

    // --- YOUR ORIGINAL ALGORITHMS (With sleep/repaint hooks) ---

    public void sisyphusSort(int[] list) throws InterruptedException {
        // Start fresh with the new array generated by fillList
        ArrayList<Integer> adaptableList = new ArrayList<>();
        for (int val : list) { adaptableList.add(val); }
        
        while (!Thread.interrupted()) {
            for (int i = 1; i < adaptableList.size(); i++) {
                int currentElement = adaptableList.get(i);
                int k = i - 1;
                while (k >= 0 && (adaptableList.get(k) - currentElement) > 0) {
                    adaptableList.set(k + 1, adaptableList.get(k));
                    k--;
                    updateVisuals(adaptableList, 10);
                }
                adaptableList.set(k + 1, currentElement);
            }
            
            // The rock drops at the bottom of the hill
            adaptableList.add(0, (int)(Math.random() * 101));
            updateVisuals(adaptableList, 600); 
        }
    }

    public void capitalismSort(int[] list) throws InterruptedException {
        int total = 0;
        for(int num: list) {total+= num;}
        int average = (total / list.length);

        for (int i = 1; i < list.length; i++){
            int currentElement = list[i];
            int k = i - 1;
            currentElement = (currentElement >= average) ? currentElement * 2 : currentElement * -2;

            while (k >= 0 && (list[k] - currentElement) > 0) {
                list[k + 1] = list[k];
                k--;
                updateVisuals(list, 50);
            }
            list[k + 1] = currentElement;
        }
    }

    public void communismSort(int[] list) throws InterruptedException {
        int total = 0;
        for(int num: list) {total+= num;}
        int average = (total / list.length);

        for(int i = 0; i < list.length; i++){
            list[i] = average;
            updateVisuals(list, 100);
        }
    }

    public void assasinSort(int[] list) throws InterruptedException {
        ArrayList<Integer> adaptableList = new ArrayList<>();
        for (int val : list) adaptableList.add(val);
        
        int maxVal = adaptableList.get(0);
        int i = 0;
        while (i < adaptableList.size()) {
            if (adaptableList.get(i) < maxVal) {
                adaptableList.remove(i);
                updateVisuals(adaptableList, 100);
            } else {
                maxVal = adaptableList.get(i);
                i++;
            }
        }
    }

    public void philCollinsSort(int[] list) throws InterruptedException {
        // Goes for 12 iterations max
        for (int i = 1; i <= Math.min(12, list.length - 1); i++){
            int currentElement = list[i];
            int k = i - 1;
            while (k >= 0 && (list[k] - currentElement) > 0) {
                list[k + 1] = list[k];
                k--;
                updateVisuals(list, 50);
            }
            list[k + 1] = currentElement;
        }
    }
    
    public void introvertSort(int[] list) throws InterruptedException {
        currentSortName = "Introvert: Tall bars fleeing to the walls...";
        
        // We will use two pointers to fill the array from the outside in
        int left = 0;
        int right = list.length - 1;

        while (left < right) {
            // 1. Find the largest value currently in the middle section
            int maxIdx = left;
            for (int i = left; i <= right; i++) {
                if (list[i] > list[maxIdx]) {
                    maxIdx = i;
                }
            }

            // 2. Decide which "exit" (left or right) is closer to the max value
            // This makes the animation look more natural/frantic
            if (Math.abs(maxIdx - left) < Math.abs(maxIdx - right)) {
                // Move it to the left edge
                int temp = list[left];
                list[left] = list[maxIdx];
                list[maxIdx] = temp;
                left++;
            } else {
                // Move it to the right edge
                int temp = list[right];
                list[right] = list[maxIdx];
                list[maxIdx] = temp;
                right--;
            }

            updateVisuals(list, 100);
        }
        currentSortName = "Introvert: Peace at last.";
    }

    public void midlifeCrisisSort(int[] list) throws InterruptedException {
        int[] original = Arrays.copyOf(list, list.length); // Remember "the glory days"
        currentSortName = "Midlife Crisis: Doing great so far...";
        
        // Phase 1: Sort the first half perfectly
        for (int i = 1; i < list.length / 2; i++) {
            int current = list[i];
            int k = i - 1;
            while (k >= 0 && list[k] > current) {
                list[k + 1] = list[k];
                k--;
                updateVisuals(list, 50);
            }
            list[k + 1] = current;
        }
        
        // Phase 2: The realization
        Thread.sleep(1000);
        currentSortName = "Midlife Crisis: Wait, what am I doing with my life?";
        updateVisuals(list, 1000);
        
        // Phase 3: The reset
        this.nums = Arrays.copyOf(original, original.length);
        currentSortName = "Midlife Crisis: I'm going back to how I used to be.";
        repaint();
    }

    public void bureaucracySort(int[] list) throws InterruptedException {
        currentSortName = "Bureaucracy: Processing swap requests...";
        boolean sorted = false;
        while (!sorted) {
            sorted = true;
            for (int i = 0; i < list.length - 1; i++) {
                if (list[i] > list[i + 1]) {
                    sorted = false;
                    // Only swap if the "Bureau of Sorting" approves (1 in 5 chance)
                    if ((int)(Math.random() * 5) == 0) {
                        int temp = list[i];
                        list[i] = list[i + 1];
                        list[i + 1] = temp;
                        currentSortName = "Bureaucracy: Swap Approved!";
                    } else {
                        currentSortName = "Bureaucracy: Swap Denied. Please resubmit.";
                    }
                    updateVisuals(list, 30);
                }
            }
        }
    }
    


    // --- VISUAL & UTILITY CODE ---

    private void updateVisuals(int[] current, int ms) throws InterruptedException {
        this.nums = Arrays.copyOf(current, current.length);
        repaint();
        Thread.sleep(ms);
    }

    private void updateVisuals(ArrayList<Integer> current, int ms) throws InterruptedException {
        this.nums = current.stream().mapToInt(v -> v).toArray();
        repaint();
        Thread.sleep(ms);
    }

    public void fillList(int[] list) {
        for(int i = 0; i < list.length; i++) list[i] = (int)(Math.random() * 101);
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        int barWidth = Math.max(2, getWidth() / Math.max(1, nums.length));
        int centerY = getHeight() / 2;

        g.drawString("Active: " + currentSortName, 10, 20);

        for (int i = 0; i < nums.length; i++) {
            int h = nums[i] * 2;
            if (nums[i] < 0) {
                g.setColor(Color.RED);
                g.fillRect(i * barWidth, centerY, barWidth - 1, Math.abs(h));
            } else {
                g.setColor(new Color(100, 150, 255));
                g.fillRect(i * barWidth, centerY - h, barWidth - 1, h);
            }
        }
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("The Esoteric Sorter");
        SortingVisualizer visualizer = new SortingVisualizer();
        
        // Control Panel
        JPanel controls = new JPanel();
        String[] options = {"Sisyphus", "Capitalism", "Communism", "Assassin", "Introvert", "Midlife Crisis", "Bureaucracy"};
        JComboBox<String> menu = new JComboBox<>(options);
        JButton runBtn = new JButton("Run Sort");
        
        runBtn.addActionListener(e -> {
            visualizer.startAlgorithm((String) menu.getSelectedItem());
        });

        controls.add(new JLabel("Choose Logic:"));
        controls.add(menu);
        controls.add(runBtn);

        frame.setLayout(new BorderLayout());
        frame.add(visualizer, BorderLayout.CENTER);
        frame.add(controls, BorderLayout.SOUTH);

        frame.setSize(800, 600);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
    }
}